### ISSUE TITLE
Issue: usage column is sorted as text, not as numbers

### ISSUE THREAD

**Issue by skfd** [AmraouiH/Entity-Field-Analyser#1] opened 2023-11-29 16:48 UTC
Here is how it looks!
![image](https://github.com/AmraouiH/Entity-Field-Analyser/assets/159640/f0cb8e50-8269-435d-b215-161cfa0b582f)

**Comment by AmraouiH** [comment] 2024-01-14 14:33
Hello @skfd, 
Glad to hear from you.
The issue is fixed on version 2.0.0.5
Thank you for your report.
Hamza

**Closed as completed** 2024-01-16 08:50 UTC
